=== bensamazingsoft/BAS-Versions/BAS-Versions/src/com/bas/versions/xml/CheckPoint.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:attribute name="id" type="xs:int"></xs:attribute>
	<xs:attribute name="date" type="xs:dateTime"></xs:attribute>
	<xs:attribute name="projectPath" type="xs:string"></xs:attribute>
	<xs:attribute name="checkpointPath" type="xs:string"></xs:attribute>


	<xs:element name="message" type="xs:string"></xs:element>

	<xs:element name="files">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="file" type="xs:string" minOccurs="1"
					maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkpoint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message"></xs:element>
				<xs:element ref="files"></xs:element>
			</xs:sequence>
			<xs:attribute ref="id" use="required"></xs:attribute>
			<xs:attribute ref="date" use="required"></xs:attribute>
			<xs:attribute ref="projectPath" use="required"></xs:attribute>
			<xs:attribute ref="checkpointPath" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== bensamazingsoft/BAS-Versions/BAS-Versions/src/SaveCheckPoint 0001[rhjdeyjr].xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<checkpoint checkpointPath="E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]"
	date="2017-08-12T18:22:00" id="1" projectPath="E:\projet"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
	xs:noNamespaceSchemaLocation="com/bas/versions/xml/CheckPoint.xsd">
	
  <message>rhjdeyjr</message>
  <files>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau dossier\Nouveau document texte.txt</file>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau document texte - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie (4) - Copie.txt</file>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau document texte - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie (3).txt</file>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau dossier\Nouveau document texte (2).txt</file>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau document texte - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie.txt</file>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau document texte - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie.txt</file>
    <file>E:\projet\BAS-CheckPoints\Checkpoint0001[2017-08-12_18-22]\Nouveau document texte - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie - Copie (3).txt</file>
  </files>
</checkpoint>
